# Generated by Django 4.0.4 on 2023-04-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Пост'},
        ),
    ]
