# Generated by Django 4.0.4 on 2023-04-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_book_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
